language: python
python:
- '3.8'
services:
- postgresql
addons:
  postgresql: '9.6'
install:
- pip install -r requirements.txt
before_script:
- psql --version
- psql -c 'create database pack_smart_dev;' -U postgres
- psql -c 'create database pack_smart_test;' -U postgres
env:
  - DATABASE_URL=postgresql://localhost:5432/pack_smart_dev
script:
- export DATABASE_URL=postgresql://localhost:5432/pack_smart_dev
- python3 manage.py db upgrade
- export DATABASE_URL=postgresql://localhost:5432/pack_smart_test
- python3 manage.py db upgrade
- python3 manage.py db_seed
- pytest
deploy:
  provider: heroku
  api_key:
    secure: "RUKxwZH7R89v//xKiGsiKyCzTqut4T+HQLTgq8Kgg5ibZArpr5s7fdpCakSO0lwR/bLfo6pCeH91m0kPgNLtI/eHuF/rmaqKooLK3537VVIqb8iY6FW0Mxry0euieyDikoe4BUExxwUaWBfSVebqzPmLdR7Iax8Q5X4/D/OTumw/V2m9WO9ZU59saSMaxuMNJwbsTGH/no7zlE3aaC1CzA1Akc18cT17ZICLFJ927j5mkZnfYkp+d7dVyyLgV6rh9uTpb/Ar5LBlrwxf9mQ6Q5Ds1ms0fNyQw9ikfPOwFrTlr/UMcQc4noEUoCTMYSbWqab/LNFlWE3mCxyAHskOdYSJR9yRE5NL850Guaen3aKVlPuiBcI4ZECO2h4Ee9sFuKdBLmzm3UNMbqhtwm3Vzjj8Vt9MwwB11QXLeG86YvrH9/TjjY30P6ns9eNEkhIX/ce8kbSdRWUxAPl+VhLyi7TgX3dlFPHhgVcLEeXxyXgeSGJ4b4eOeqiMb5XeOC85Otr5e4Rv5dTI1w9kL7gTVcDdP0ljQo6lcOwxC4wecF2SrXEeSAeVCMrLrkq0y2JztJLN0gDMoZkKrUFluq3x2fgka9x5R9m5ee8t+aSLfwR4z079iBQvSSvjgANTaTEVCA7BRGCVYBRABnEO48gUpzh9EL8o7Qdx6UjMjaJx6zE="
  app: pack-smart-be
  on:
    repo: Pack-Smart/pack-smart-be
    branch: main
  skip_cleanup: 'true'
  run:
    - pip install -r requirements.txt
    - createdb pack_smart_dev
    - python manage.py db upgrade
    - python manage.py db_seed

