"""empty message

Revision ID: 7aeaaee42cca
Revises: e8f29043f084
Create Date: 2021-02-25 16:41:53.128348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aeaaee42cca'
down_revision = 'e8f29043f084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('packing_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_title', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('num_of_days', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('packing_list_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['packing_list_id'], ['packing_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('items', sa.Column('item', sa.String(length=80), nullable=False))
    op.drop_column('items', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('items', 'item')
    op.drop_table('item_lists')
    op.drop_table('packing_lists')
    op.drop_table('users')
    # ### end Alembic commands ###
