"""empty message

Revision ID: a38d158e5bce
Revises: 7aeaaee42cca
Create Date: 2021-03-01 20:15:08.008790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38d158e5bce'
down_revision = '7aeaaee42cca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('packing_list_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['packing_list_id'], ['packing_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_items')
    # ### end Alembic commands ###
