"""empty message

Revision ID: e2f3e9082c71
Revises: 7aeaaee42cca
Create Date: 2021-02-28 16:12:43.339058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f3e9082c71'
down_revision = '7aeaaee42cca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packing_lists', sa.Column('title', sa.String(length=80), nullable=False))
    op.drop_column('packing_lists', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packing_lists', sa.Column('title', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('packing_lists', 'title')
    # ### end Alembic commands ###
